# Generated by Django 5.2.4 on 2026-01-30 13:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='xaridor ismi')),
                ('phone_number', models.CharField(max_length=255, verbose_name='xaridor telefon raqami')),
                ('address', models.CharField(max_length=255, verbose_name='xaridor manzili')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debitor', models.CharField(max_length=255, verbose_name='qarzdor')),
                ('description', models.TextField(verbose_name='qarz tavsifi')),
                ('date', models.DateField(verbose_name='qarz sanasi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='miqdori')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='qoldiq')),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'debts',
            },
        ),
        migrations.CreateModel(
            name='Material_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField()),
                ('reserved_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'material_stock',
            },
        ),
        migrations.CreateModel(
            name='Model_part_definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_variant_selectable', models.BooleanField()),
                ('is_required', models.BooleanField()),
                ('quantity_per_pair', models.FloatField()),
                ('waste_percent', models.FloatField()),
            ],
            options={
                'db_table': 'model_part_definition',
            },
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='buyurtma miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='buyurtma narxi')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='buyurtma jami narxi')),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Order_details',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'purchase',
            },
        ),
        migrations.CreateModel(
            name='references',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Status'), (2, 'Gender'), (3, 'Color'), (4, 'Profession'), (5, 'Quantity_Type'), (6, 'Currency'), (10, 'Model'), (11, 'Model_Part'), (20, 'Material_Type'), (21, 'Stock_Movement_Type'), (30, 'Leather_Variant'), (31, 'Sole_Variant'), (32, 'Lining_Variant'), (33, 'Glue_Variant'), (34, 'Textile_Variant')], verbose_name='Reference Type')),
                ('value', models.CharField(max_length=255)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsSystem', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'references',
            },
        ),
        migrations.CreateModel(
            name='shoe_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='oyoq kiyim nomi')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='oyoq kiyim kodi')),
                ('image', models.ImageField(upload_to='media/', verbose_name='oyoq kiyim rasmi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'shoe_model',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='client_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='tulov sanasi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='miqdori')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('IsDeleted', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id_clients', to='home.clients', verbose_name='xaridor')),
            ],
            options={
                'db_table': 'client_payments',
            },
        ),
        migrations.CreateModel(
            name='Order_detail_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('material_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_parts', to='home.material_stock')),
                ('model_part_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_parts', to='home.model_part_definition')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='home.order_details')),
            ],
            options={
                'db_table': 'order_detail_parts',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Buyurtma sanasi')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='buyurtma jami narxi')),
                ('complete_date', models.DateField(verbose_name='buyurtma topshirish sanasi')),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsSystem', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='home.clients', verbose_name='xaridor')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_orders', to='home.references', verbose_name='buyurtma xolati')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='order_details',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id_orders', to='home.orders', verbose_name='Buyurtma'),
        ),
        migrations.CreateModel(
            name='Purchase_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_id_purchase_item', to='home.material_stock')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_id', to='home.purchase')),
            ],
            options={
                'db_table': 'purchase_item',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_status', to='home.references'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='quantity_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_type_orders', to='home.references', verbose_name='buyurtma miqdor turi'),
        ),
        migrations.AddField(
            model_name='model_part_definition',
            name='default_variant_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_variant_ref_id', to='home.references'),
        ),
        migrations.AddField(
            model_name='model_part_definition',
            name='material_type_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_type_ref_id', to='home.references'),
        ),
        migrations.AddField(
            model_name='model_part_definition',
            name='part_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_ref_id', to='home.references'),
        ),
        migrations.AddField(
            model_name='model_part_definition',
            name='unit_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_ref_id', to='home.references'),
        ),
        migrations.AddField(
            model_name='material_stock',
            name='color_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_ref_id_stock', to='home.references'),
        ),
        migrations.AddField(
            model_name='material_stock',
            name='material_type_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_type_ref_id_stock', to='home.references'),
        ),
        migrations.AddField(
            model_name='material_stock',
            name='unit_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_ref_id_stock', to='home.references'),
        ),
        migrations.AddField(
            model_name='material_stock',
            name='variant_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_ref_id_stock', to='home.references'),
        ),
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='xarajat sanasi')),
                ('description', models.TextField(verbose_name='xarajat tavsifi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='xarajat miqdori')),
                ('IsDeleted', models.BooleanField(default=False)),
                ('debt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_id_expenses', to='home.debts', verbose_name='xarajat qarzi')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_expenses', to='home.references', verbose_name='xarajat turi')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.AddField(
            model_name='debts',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_currency', to='home.references', verbose_name='qarz pul birligi'),
        ),
        migrations.AddField(
            model_name='clients',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_reference_client', to='home.references'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_id_orders', to='home.shoe_model', verbose_name='buyurtma modeli'),
        ),
        migrations.AddField(
            model_name='model_part_definition',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_part_definition_shoe_model', to='home.shoe_model'),
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='xodim ismi')),
                ('birth_date', models.DateField(verbose_name="xodim to'g'ilgan sanasi")),
                ('entered_date', models.DateField(verbose_name='xodim ishga kirgan sanasi')),
                ('phone_number', models.CharField(max_length=255, verbose_name='xodim telefon raqami')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_reference', to='home.references', verbose_name='xodim jinsi')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_reference', to='home.references', verbose_name='xodim kasbi')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='producement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="ish qo'shilgan sanasi")),
                ('quantity', models.IntegerField(verbose_name='ish miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='ish narxi')),
                ('IsDeleted', models.BooleanField(default=False)),
                ('order_detail_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_id_producement', to='home.order_details', verbose_name='Buyurma malumotlari')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_producement', to='home.orders', verbose_name='ish buyurtmasi')),
                ('producement_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_producement', to='home.producement')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_id_producement', to='home.references', verbose_name='ish rangi')),
                ('leather_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leather_type_reference', to='home.references', verbose_name='terisi')),
                ('lining_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lining_type_producement', to='home.references')),
                ('quantity_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_type_producement', to='home.references', verbose_name='ish miqdor turi')),
                ('solo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solo_type_reference', to='home.references', verbose_name='tagliki')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_producement', to='home.references', verbose_name='ish xolati')),
                ('toqa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toqa_producement', to='home.references')),
                ('shoe_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_model_id_producement', to='home.shoe_model', verbose_name='ish modeli')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id_staff_producement', to='home.staff', verbose_name='xodim')),
            ],
            options={
                'db_table': 'producement',
            },
        ),
        migrations.CreateModel(
            name='staff_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='tulov sanasi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='miqdori')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('IsDeleted', models.BooleanField(default=False)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id_staff', to='home.staff', verbose_name='xodim')),
            ],
            options={
                'db_table': 'staff_payments',
            },
        ),
        migrations.CreateModel(
            name='Stock_movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='home.material_stock')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='home.references')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='home.orders')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='home.purchase')),
            ],
            options={
                'db_table': 'stock_movement',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_id', to='home.supplier'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='buyurtma miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_id_warehouse', to='home.references', verbose_name='buyurtma rangi')),
                ('leather_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leather_type_warehouse', to='home.references', verbose_name='terisi')),
                ('lining_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lining_type_warehouse', to='home.references')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_id_warehouse', to='home.shoe_model', verbose_name='buyurtma modeli')),
                ('quantity_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_type_warehouse', to='home.references', verbose_name='buyurtma miqdor turi')),
                ('sole_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sole_type_warehouse', to='home.references')),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sales', to='home.clients')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_sales', to='home.warehouse')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
