# Generated by Django 5.1.3 on 2024-11-27 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='xaridor ismi')),
                ('phone_number', models.CharField(max_length=255, verbose_name='xaridor telefon raqami')),
                ('address', models.CharField(max_length=255, verbose_name='xaridor manzili')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debitor', models.CharField(max_length=255, verbose_name='qarzdor')),
                ('description', models.TextField(verbose_name='qarz tavsifi')),
                ('date', models.DateField(verbose_name='qarz sanasi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='miqdori')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='qoldiq')),
            ],
            options={
                'db_table': 'debts',
            },
        ),
        migrations.CreateModel(
            name='references',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name="ma'lumotnoma turi")),
                ('value', models.CharField(max_length=255, verbose_name="ma'lumotnoma qiymati")),
            ],
            options={
                'db_table': 'references',
            },
        ),
        migrations.CreateModel(
            name='shoe_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='oyoq kiyim nomi')),
                ('code', models.CharField(max_length=255, verbose_name='oyoq kiyim kodi')),
                ('image', models.ImageField(upload_to='media/', verbose_name='oyoq kiyim rasmi')),
                ('description', models.TextField(verbose_name='oyoq kiyim tavsifi')),
            ],
            options={
                'db_table': 'shoe_model',
            },
        ),
        migrations.CreateModel(
            name='client_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='tulov sanasi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='miqdori')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_id_clients', to='home.clients', verbose_name='xaridor')),
            ],
            options={
                'db_table': 'client_payments',
            },
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Buyurtma sanasi')),
                ('quantity', models.IntegerField(verbose_name='buyurtma miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='buyurtma narxi')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='buyurtma jami narxi')),
                ('complete_date', models.DateField(verbose_name='buyurtma topshirish sanasi')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_orders', to='home.clients', verbose_name='xaridor')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='color_id_orders', to='home.references', verbose_name='buyurtma rangi')),
                ('leather_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leather_id_reference', to='home.references', verbose_name='terisi')),
                ('quantity_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantity_type_orders', to='home.references', verbose_name='buyurtma miqdor turi')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_orders', to='home.references', verbose_name='buyurtma xolati')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_id_orders', to='home.shoe_model', verbose_name='buyurtma modeli')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='xarajat sanasi')),
                ('description', models.TextField(verbose_name='xarajat tavsifi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='xarajat miqdori')),
                ('debt_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='debt_id_expenses', to='home.debts', verbose_name='xarajat qarzi')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='type_expenses', to='home.references', verbose_name='xarajat turi')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.AddField(
            model_name='debts',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='debts_currency', to='home.references', verbose_name='qarz pul birligi'),
        ),
        migrations.AddField(
            model_name='clients',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='currency_reference_client', to='home.references'),
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='xodim ismi')),
                ('birth_date', models.DateField(verbose_name="xodim to'g'ilgan sanasi")),
                ('entered_date', models.DateField(verbose_name='xodim ishga kirgan sanasi')),
                ('phone_number', models.CharField(max_length=255, verbose_name='xodim telefon raqami')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gender_reference', to='home.references', verbose_name='xodim jinsi')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profession_reference', to='home.references', verbose_name='xodim kasbi')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='producement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="ish qo'shilgan sanasi")),
                ('quantity', models.IntegerField(verbose_name='ish miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='ish narxi')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_producement', to='home.orders', verbose_name='ish buyurtmasi')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='color_id_producement', to='home.references', verbose_name='ish rangi')),
                ('leather_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leather_type_reference', to='home.references', verbose_name='terisi')),
                ('quantity_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quantity_type_producement', to='home.references', verbose_name='ish miqdor turi')),
                ('solo_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solo_type_reference', to='home.references', verbose_name='tagliki')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_producement', to='home.references', verbose_name='ish xolati')),
                ('shoe_model_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shoe_model_id_producement', to='home.shoe_model', verbose_name='ish modeli')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_id_staff_producement', to='home.staff', verbose_name='xodim')),
            ],
            options={
                'db_table': 'producement',
            },
        ),
        migrations.CreateModel(
            name='staff_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='tulov sanasi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='miqdori')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_id_staff', to='home.staff', verbose_name='xodim')),
            ],
            options={
                'db_table': 'staff_payments',
            },
        ),
    ]
