# Generated by Django 5.2.4 on 2025-10-20 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='xaridor ismi')),
                ('phone_number', models.CharField(max_length=255, verbose_name='xaridor telefon raqami')),
                ('address', models.CharField(max_length=255, verbose_name='xaridor manzili')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debitor', models.CharField(max_length=255, verbose_name='qarzdor')),
                ('description', models.TextField(verbose_name='qarz tavsifi')),
                ('date', models.DateField(verbose_name='qarz sanasi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='miqdori')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='qoldiq')),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'debts',
            },
        ),
        migrations.CreateModel(
            name='references',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Status'), (2, 'Gender'), (3, 'Color'), (4, 'Leather_Type'), (5, 'Profession'), (6, 'Quantity_Type'), (7, 'Currency'), (8, 'Solo_Type'), (9, 'Lining_Type')], verbose_name='Reference Type')),
                ('value', models.CharField(max_length=255)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsSystem', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'references',
            },
        ),
        migrations.CreateModel(
            name='shoe_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='oyoq kiyim nomi')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='oyoq kiyim kodi')),
                ('image', models.ImageField(upload_to='media/', verbose_name='oyoq kiyim rasmi')),
                ('description', models.TextField(verbose_name='oyoq kiyim tavsifi')),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'shoe_model',
            },
        ),
        migrations.CreateModel(
            name='client_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='tulov sanasi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='miqdori')),
                ('IsDeleted', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id_clients', to='home.clients', verbose_name='xaridor')),
            ],
            options={
                'db_table': 'client_payments',
            },
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Buyurtma sanasi')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='buyurtma jami narxi')),
                ('complete_date', models.DateField(verbose_name='buyurtma topshirish sanasi')),
                ('IsDeleted', models.BooleanField(default=False)),
                ('IsSystem', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='home.clients', verbose_name='xaridor')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_orders', to='home.references', verbose_name='buyurtma xolati')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='buyurtma miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='buyurtma narxi')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='buyurtma jami narxi')),
                ('IsDeleted', models.BooleanField(default=False)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordeer_id_orders', to='home.orders', verbose_name='Buyurtma')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_id_orders', to='home.references', verbose_name='buyurtma rangi')),
                ('leather_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leather_type_Orders', to='home.references', verbose_name='terisi')),
                ('lining_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lining_type_orders', to='home.references')),
                ('quantity_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_type_orders', to='home.references', verbose_name='buyurtma miqdor turi')),
                ('sole_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sole_type_orders', to='home.references')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_id_orders', to='home.shoe_model', verbose_name='buyurtma modeli')),
            ],
            options={
                'db_table': 'Order_details',
            },
        ),
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='xarajat sanasi')),
                ('description', models.TextField(verbose_name='xarajat tavsifi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='xarajat miqdori')),
                ('IsDeleted', models.BooleanField(default=False)),
                ('debt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_id_expenses', to='home.debts', verbose_name='xarajat qarzi')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_expenses', to='home.references', verbose_name='xarajat turi')),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.AddField(
            model_name='debts',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_currency', to='home.references', verbose_name='qarz pul birligi'),
        ),
        migrations.AddField(
            model_name='clients',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_reference_client', to='home.references'),
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='xodim ismi')),
                ('birth_date', models.DateField(verbose_name="xodim to'g'ilgan sanasi")),
                ('entered_date', models.DateField(verbose_name='xodim ishga kirgan sanasi')),
                ('phone_number', models.CharField(max_length=255, verbose_name='xodim telefon raqami')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_reference', to='home.references', verbose_name='xodim jinsi')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_reference', to='home.references', verbose_name='xodim kasbi')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='producement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="ish qo'shilgan sanasi")),
                ('quantity', models.IntegerField(verbose_name='ish miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='ish narxi')),
                ('IsDeleted', models.BooleanField(default=False)),
                ('order_detail_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_id_producement', to='home.order_details', verbose_name='Buyurma malumotlari')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_producement', to='home.orders', verbose_name='ish buyurtmasi')),
                ('producement_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_producement', to='home.producement')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_id_producement', to='home.references', verbose_name='ish rangi')),
                ('leather_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leather_type_reference', to='home.references', verbose_name='terisi')),
                ('lining_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lining_type_producement', to='home.references')),
                ('quantity_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_type_producement', to='home.references', verbose_name='ish miqdor turi')),
                ('solo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solo_type_reference', to='home.references', verbose_name='tagliki')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_producement', to='home.references', verbose_name='ish xolati')),
                ('shoe_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_model_id_producement', to='home.shoe_model', verbose_name='ish modeli')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id_staff_producement', to='home.staff', verbose_name='xodim')),
            ],
            options={
                'db_table': 'producement',
            },
        ),
        migrations.CreateModel(
            name='staff_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='tulov sanasi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='miqdori')),
                ('IsDeleted', models.BooleanField(default=False)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id_staff', to='home.staff', verbose_name='xodim')),
            ],
            options={
                'db_table': 'staff_payments',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='buyurtma miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_id_warehouse', to='home.references', verbose_name='buyurtma rangi')),
                ('leather_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leather_type_warehouse', to='home.references', verbose_name='terisi')),
                ('lining_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lining_type_warehouse', to='home.references')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_id_warehouse', to='home.shoe_model', verbose_name='buyurtma modeli')),
                ('quantity_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_type_warehouse', to='home.references', verbose_name='buyurtma miqdor turi')),
                ('sole_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sole_type_warehouse', to='home.references')),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sales', to='home.clients')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_sales', to='home.warehouse')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
