# Generated by Django 5.1.3 on 2024-12-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='references',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='references',
            name='IsSystem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producement',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_producement', to='home.orders', verbose_name='ish buyurtmasi'),
        ),
        migrations.AlterField(
            model_name='references',
            name='type',
            field=models.IntegerField(choices=[(1, 'Status'), (2, 'Gender'), (3, 'Color'), (4, 'Leather_Type'), (5, 'Profession'), (6, 'Quantity_Type'), (7, 'Currency')], verbose_name='Reference Type'),
        ),
        migrations.AlterField(
            model_name='shoe_model',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='oyoq kiyim kodi'),
        ),
    ]
