# Generated by Django 5.1.3 on 2025-02-13 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producement',
            name='order_detail_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_id_producement', to='home.order_details', verbose_name='Buyurma malumotlari'),
        ),
    ]
