# Generated by Django 5.2.4 on 2026-02-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_part_definition',
            name='default_variant_ref_id',
        ),
        migrations.RemoveField(
            model_name='model_part_definition',
            name='is_variant_selectable',
        ),
        migrations.RemoveField(
            model_name='producement',
            name='color_id',
        ),
        migrations.RemoveField(
            model_name='producement',
            name='leather_type',
        ),
        migrations.RemoveField(
            model_name='producement',
            name='lining_type_id',
        ),
        migrations.RemoveField(
            model_name='producement',
            name='producement_id',
        ),
        migrations.RemoveField(
            model_name='producement',
            name='solo_type',
        ),
        migrations.RemoveField(
            model_name='producement',
            name='toqa_id',
        ),
        migrations.AlterField(
            model_name='references',
            name='type',
            field=models.IntegerField(choices=[(1, 'Status'), (2, 'Gender'), (3, 'Color'), (4, 'Profession'), (5, 'Quantity_Type'), (6, 'Currency'), (10, 'Model'), (11, 'Model_Part'), (20, 'Material_Type'), (21, 'Stock_Movement_Type'), (30, 'Leather_Variant'), (31, 'Sole_Variant'), (32, 'Lining_Variant'), (33, 'Glue_Variant'), (34, 'Textile_Variant'), (35, 'Thread_Variant'), (36, 'Mix_Variant'), (37, 'Box_Variant'), (38, 'Buckle_Variant'), (39, 'Elastic_Variant'), (40, 'Rivet_Variant'), (41, 'Cardboard_Variant'), (42, 'Cloth_Variant'), (43, 'Visor_Variant'), (44, 'Paper_Variant'), (45, 'Stretch_Variant'), (46, 'Fur_Variant'), (47, 'Zipper_Variant'), (48, 'Sponge_Variant'), (49, 'Velcro_Variant')], verbose_name='Reference Type'),
        ),
        migrations.AlterField(
            model_name='shoe_model',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
    ]
