# Generated by Django 5.1.3 on 2025-05-01 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='IsSystem',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Buyurtma sanasi'),
        ),
        migrations.AlterField(
            model_name='references',
            name='type',
            field=models.IntegerField(choices=[(1, 'Status'), (2, 'Gender'), (3, 'Color'), (4, 'Leather_Type'), (5, 'Profession'), (6, 'Quantity_Type'), (7, 'Currency'), (8, 'Solo_Type'), (9, 'Lining_Type')], verbose_name='Reference Type'),
        ),
    ]
