# Generated by Django 5.1.3 on 2025-02-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_producement_order_detail_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='leather_id',
        ),
    ]
