# Generated by Django 5.1.3 on 2024-12-20 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_references_isdeleted_references_issystem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_payments',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id_clients', to='home.clients', verbose_name='xaridor'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_reference_client', to='home.references'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_currency', to='home.references', verbose_name='qarz pul birligi'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='debt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_id_expenses', to='home.debts', verbose_name='xarajat qarzi'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_expenses', to='home.references', verbose_name='xarajat turi'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='home.clients', verbose_name='xaridor'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_id_orders', to='home.references', verbose_name='buyurtma rangi'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='leather_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leather_id_reference', to='home.references', verbose_name='terisi'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_id_orders', to='home.shoe_model', verbose_name='buyurtma modeli'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_type_orders', to='home.references', verbose_name='buyurtma miqdor turi'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_orders', to='home.references', verbose_name='buyurtma xolati'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_id_producement', to='home.references', verbose_name='ish rangi'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='leather_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leather_type_reference', to='home.references', verbose_name='terisi'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_producement', to='home.orders', verbose_name='ish buyurtmasi'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='quantity_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_type_producement', to='home.references', verbose_name='ish miqdor turi'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='shoe_model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_model_id_producement', to='home.shoe_model', verbose_name='ish modeli'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='solo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_type_reference', to='home.references', verbose_name='tagliki'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id_staff_producement', to='home.staff', verbose_name='xodim'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_producement', to='home.references', verbose_name='ish xolati'),
        ),
        migrations.AlterField(
            model_name='references',
            name='type',
            field=models.IntegerField(choices=[(1, 'Status'), (2, 'Gender'), (3, 'Color'), (4, 'Leather_Type'), (5, 'Profession'), (6, 'Quantity_Type'), (7, 'Currency'), (8, 'Solo_Type')], verbose_name='Reference Type'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_reference', to='home.references', verbose_name='xodim jinsi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_reference', to='home.references', verbose_name='xodim kasbi'),
        ),
        migrations.AlterField(
            model_name='staff_payments',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id_staff', to='home.staff', verbose_name='xodim'),
        ),
    ]
