# Generated by Django 5.2.4 on 2025-11-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_client_payments_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client_payments',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
        migrations.AlterField(
            model_name='shoe_model',
            name='description',
            field=models.TextField(verbose_name='tavsif'),
        ),
        migrations.AlterField(
            model_name='staff_payments',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='tavsif'),
        ),
    ]
