# Generated by Django 5.1.3 on 2025-05-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_orders_issystem_alter_orders_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='references',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
