# Generated by Django 5.2.4 on 2025-12-16 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_clients_is_system_alter_client_payments_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='toqa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toqa_details', to='home.references'),
        ),
        migrations.AddField(
            model_name='producement',
            name='toqa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toqa_producement', to='home.references'),
        ),
        migrations.AlterField(
            model_name='references',
            name='type',
            field=models.IntegerField(choices=[(1, 'Status'), (2, 'Gender'), (3, 'Color'), (4, 'Leather_Type'), (5, 'Profession'), (6, 'Quantity_Type'), (7, 'Currency'), (8, 'Solo_Type'), (9, 'Lining_Type'), (10, 'Toqa')], verbose_name='Reference Type'),
        ),
    ]
