# Generated by Django 5.2.4 on 2026-05-04 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_model_part_definition_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_details',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_id_orders', to='home.shoe_model'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id_orders', to='home.orders'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='supplier',
        ),
    ]
