# Generated by Django 5.1.3 on 2024-12-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_client_payments_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=20),
            preserve_default=False,
        ),
    ]
