# Generated by Django 5.1.3 on 2024-12-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_clients_balance_staff_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
