# Generated by Django 5.2.4 on 2026-05-14 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_purchase_paid_amount_supplier_isdeleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_stock',
            name='available_quantity',
        ),
        migrations.AlterField(
            model_name='material_stock',
            name='color_ref_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_ref_id_stock', to='home.references'),
        ),
    ]
