# Generated by Django 5.1.3 on 2025-06-03 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_producement_producement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producement',
            name='solo_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solo_type_reference', to='home.references', verbose_name='tagliki'),
        ),
    ]
