# Generated by Django 5.2.4 on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_material_stock_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail_parts',
            name='quantity_required',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
