# Generated by Django 5.1.3 on 2025-06-22 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_producement_solo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producement',
            name='producement_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_producement', to='home.producement'),
        ),
    ]
