# Generated by Django 5.2.4 on 2025-08-15 11:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_producement_producement_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='buyurtma miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_id_warehouse', to='home.references', verbose_name='buyurtma rangi')),
                ('leather_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leather_type_warehouse', to='home.references', verbose_name='terisi')),
                ('lining_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lining_type_warehouse', to='home.references')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_id_warehouse', to='home.shoe_model', verbose_name='buyurtma modeli')),
                ('quantity_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_type_warehouse', to='home.references', verbose_name='buyurtma miqdor turi')),
                ('sole_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sole_type_warehouse', to='home.references')),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sales', to='home.clients')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_sales', to='home.warehouse')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
