# Generated by Django 5.2.4 on 2026-07-08 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_stock_movement_nullable_and_decimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Narxi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_stock_sales', to='home.clients', verbose_name='Xaridor')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sales', to='home.order_details', verbose_name='Ombor')),
            ],
            options={
                'db_table': 'stock_sale',
            },
        ),
        migrations.CreateModel(
            name='SupplierPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('IsDeleted', models.BooleanField(default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='home.supplier')),
            ],
            options={
                'db_table': 'supplier_payments',
            },
        ),
    ]
