# Generated by Django 5.2.4 on 2026-07-08 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_stock_sale_supplierpayments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='type',
            field=models.IntegerField(choices=[(1, 'Status'), (2, 'Gender'), (3, 'Color'), (4, 'Profession'), (5, 'Quantity_Type'), (6, 'Currency'), (10, 'Model'), (11, 'Model_Part'), (20, 'Material_Type'), (21, 'Stock_Movement_Type'), (22, 'Model_Expenses_Type'), (30, 'Leather_Variant'), (31, 'Sole_Variant'), (32, 'Lining_Variant'), (33, 'Glue_Variant'), (34, 'Textile_Variant'), (35, 'Thread_Variant'), (36, 'Mix_Variant'), (37, 'Box_Variant'), (38, 'Buckle_Variant'), (39, 'Elastic_Variant'), (40, 'Rivet_Variant'), (41, 'Cardboard_Variant'), (42, 'Cloth_Variant'), (43, 'Visor_Variant'), (44, 'Paper_Variant'), (45, 'Stretch_Variant'), (46, 'Fur_Variant'), (47, 'Zipper_Variant'), (48, 'Sponge_Variant'), (49, 'Velcro_Variant')], verbose_name='Reference Type'),
        ),
        migrations.CreateModel(
            name='Model_expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('model_expenses_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_model_expenses', to='home.references')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_expenses', to='home.shoe_model')),
                ('profession_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_model_expenses', to='home.references')),
            ],
            options={
                'db_table': 'model_expenses',
            },
        ),
    ]
