# Generated by Django 5.2.4 on 2026-07-08 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_references_type_model_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_expenses',
            name='profession_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profession_model_expenses', to='home.references'),
        ),
    ]
