# Generated by Django 5.2.4 on 2026-07-13 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_model_expenses_profession_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
