# Generated by Django 5.2.4 on 2026-07-22 14:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_order_details_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_payments',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='client_payments',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='client_payments',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_id_clients', to='home.clients', verbose_name='Xaridor'),
        ),
        migrations.AlterField(
            model_name='client_payments',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='clients',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Manzili'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Balans'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_reference_client', to='home.references', verbose_name='Pul birligi'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Tizim yozuvi'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='debts',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Qoldiq'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_currency', to='home.references', verbose_name='Pul birligi'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='debitor',
            field=models.CharField(max_length=255, verbose_name='Qarzdor'),
        ),
        migrations.AlterField(
            model_name='debts',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='debt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_id_expenses', to='home.debts', verbose_name='Qarz'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_expenses', to='home.references', verbose_name='Xarajat turi'),
        ),
        migrations.AlterField(
            model_name='material_stock',
            name='color_ref_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_ref_id_stock', to='home.references', verbose_name='Rangi'),
        ),
        migrations.AlterField(
            model_name='material_stock',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='material_stock',
            name='material_type_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_type_ref_id_stock', to='home.references', verbose_name='Material turi'),
        ),
        migrations.AlterField(
            model_name='material_stock',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Band qilingan'),
        ),
        migrations.AlterField(
            model_name='material_stock',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ombordagi miqdor'),
        ),
        migrations.AlterField(
            model_name='material_stock',
            name='unit_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_ref_id_stock', to='home.references', verbose_name='Birligi'),
        ),
        migrations.AlterField(
            model_name='material_stock',
            name='updated_at',
            field=models.DateField(auto_now_add=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='material_stock',
            name='variant_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_ref_id_stock', to='home.references', verbose_name='Variant turi'),
        ),
        migrations.AlterField(
            model_name='model_expenses',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='model_expenses',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='model_expenses',
            name='model_expenses_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_model_expenses', to='home.references', verbose_name='Xarajat turi'),
        ),
        migrations.AlterField(
            model_name='model_expenses',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_expenses', to='home.shoe_model', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='model_expenses',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='model_expenses',
            name='profession_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profession_model_expenses', to='home.references', verbose_name='Kasb'),
        ),
        migrations.AlterField(
            model_name='model_expenses',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='model_part_definition',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='model_part_definition',
            name='is_required',
            field=models.BooleanField(verbose_name='Majburiy'),
        ),
        migrations.AlterField(
            model_name='model_part_definition',
            name='material_type_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_type_ref_id', to='home.references', verbose_name='Material turi'),
        ),
        migrations.AlterField(
            model_name='model_part_definition',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_part_definition_shoe_model', to='home.shoe_model', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='model_part_definition',
            name='part_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_ref_id', to='home.references', verbose_name='Model qismi'),
        ),
        migrations.AlterField(
            model_name='model_part_definition',
            name='quantity_per_pair',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Juftiga'),
        ),
        migrations.AlterField(
            model_name='model_part_definition',
            name='unit_ref_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_ref_id', to='home.references', verbose_name='Birligi'),
        ),
        migrations.AlterField(
            model_name='model_part_definition',
            name='waste_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qoldiq foizi'),
        ),
        migrations.AlterField(
            model_name='order_detail_parts',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='order_detail_parts',
            name='material_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_parts', to='home.material_stock', verbose_name='Material ombori'),
        ),
        migrations.AlterField(
            model_name='order_detail_parts',
            name='model_part_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_parts', to='home.model_part_definition', verbose_name='Model qismi'),
        ),
        migrations.AlterField(
            model_name='order_detail_parts',
            name='order_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='home.order_details', verbose_name='Buyurtma tafsilotlari'),
        ),
        migrations.AlterField(
            model_name='order_detail_parts',
            name='quantity_required',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kerak'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_id_orders', to='home.shoe_model', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id_orders', to='home.orders', verbose_name='Buyurtma'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='quantity',
            field=models.IntegerField(verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='quantity_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_type_orders', to='home.references', verbose_name='Miqdor turi'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='orders',
            name='IsSystem',
            field=models.BooleanField(default=False, verbose_name='Tizim yozuvi'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='home.clients', verbose_name='Xaridor'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='complete_date',
            field=models.DateField(verbose_name='Topshirish sanasi'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_orders', to='home.references', verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='producement',
            name='date',
            field=models.DateField(verbose_name='Ish sanasi'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='order_detail_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail_id_producement', to='home.order_details', verbose_name='Buyurtma tafsilotlari'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_producement', to='home.orders', verbose_name='Buyurtma'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='quantity',
            field=models.IntegerField(verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='quantity_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_type_producement', to='home.references', verbose_name='Miqdor turi'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='shoe_model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe_model_id_producement', to='home.shoe_model', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id_staff_producement', to='home.staff', verbose_name='Hodim'),
        ),
        migrations.AlterField(
            model_name='producement',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_producement', to='home.references', verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name="To'langan summa"),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(verbose_name='Xarid sanasi'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_status', to='home.references', verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_id', to='home.supplier', verbose_name='Yetkazib beruvchi'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_id_purchase_item', to='home.material_stock', verbose_name='Material ombori'),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='purchase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_id', to='home.purchase', verbose_name='Xarid'),
        ),
        migrations.AlterField(
            model_name='purchase_item',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='references',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='references',
            name='IsSystem',
            field=models.BooleanField(default=False, verbose_name='Tizim yozuvi'),
        ),
        migrations.AlterField(
            model_name='references',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='references',
            name='type',
            field=models.IntegerField(choices=[(1, 'Status'), (2, 'Gender'), (3, 'Color'), (4, 'Profession'), (5, 'Quantity_Type'), (6, 'Currency'), (10, 'Model'), (11, 'Model_Part'), (20, 'Material_Type'), (21, 'Stock_Movement_Type'), (22, 'Model_Expenses_Type'), (30, 'Leather_Variant'), (31, 'Sole_Variant'), (32, 'Lining_Variant'), (33, 'Glue_Variant'), (34, 'Textile_Variant'), (35, 'Thread_Variant'), (36, 'Mix_Variant'), (37, 'Box_Variant'), (38, 'Buckle_Variant'), (39, 'Elastic_Variant'), (40, 'Rivet_Variant'), (41, 'Cardboard_Variant'), (42, 'Cloth_Variant'), (43, 'Visor_Variant'), (44, 'Paper_Variant'), (45, 'Stretch_Variant'), (46, 'Fur_Variant'), (47, 'Zipper_Variant'), (48, 'Sponge_Variant'), (49, 'Velcro_Variant')], verbose_name="Ma'lumotnoma turi"),
        ),
        migrations.AlterField(
            model_name='references',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Qiymati'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='sales',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_sales', to='home.clients', verbose_name='Xaridor'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Jami narx'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_sales', to='home.warehouse', verbose_name='Ombor'),
        ),
        migrations.AlterField(
            model_name='shoe_model',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='shoe_model',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Kodi'),
        ),
        migrations.AlterField(
            model_name='shoe_model',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Model rasmi'),
        ),
        migrations.AlterField(
            model_name='shoe_model',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='staff',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Balans'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='birth_date',
            field=models.DateField(verbose_name="Tug'ilgan sanasi"),
        ),
        migrations.AlterField(
            model_name='staff',
            name='entered_date',
            field=models.DateField(verbose_name='Ishga kirgan sanasi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_reference', to='home.references', verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profession_reference', to='home.references', verbose_name='Kasb'),
        ),
        migrations.AlterField(
            model_name='staff_payments',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='staff_payments',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='staff_payments',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='staff_payments',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_id_staff', to='home.staff', verbose_name='Hodim'),
        ),
        migrations.AlterField(
            model_name='stock_movement',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='stock_movement',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='stock_movement',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='home.material_stock', verbose_name='Material ombori'),
        ),
        migrations.AlterField(
            model_name='stock_movement',
            name='movement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='home.references', verbose_name='Harakat turi'),
        ),
        migrations.AlterField(
            model_name='stock_movement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='home.orders', verbose_name='Buyurtma'),
        ),
        migrations.AlterField(
            model_name='stock_movement',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='home.purchase', verbose_name='Xarid'),
        ),
        migrations.AlterField(
            model_name='stock_movement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='stock_sale',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='stock_sale',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='stock_sale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Jami narx'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Manzili'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Balans'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Tizim yozuvi'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='supplierpayments',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='supplierpayments',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Summa'),
        ),
        migrations.AlterField(
            model_name='supplierpayments',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='supplierpayments',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payments', to='home.supplier', verbose_name='Yetkazib beruvchi'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='IsDeleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilgan"),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_id_warehouse', to='home.references', verbose_name='Rangi'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='leather_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leather_type_warehouse', to='home.references', verbose_name='Teri turi'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='lining_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lining_type_warehouse', to='home.references', verbose_name='Astar turi'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_id_warehouse', to='home.shoe_model', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='quantity',
            field=models.IntegerField(verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='quantity_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_type_warehouse', to='home.references', verbose_name='Miqdor turi'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='sole_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sole_type_warehouse', to='home.references', verbose_name='Taglik turi'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Jami summa'),
        ),
    ]
