# General Labels and Titles
ID = "ID"
TITLE = "Chelsea shoes"
BRAND_NAME = "Chelsea"
SEARCH = "Qidiruv..."
LOG_OUT = "Chiqish"

# Buttons and Actions
CREATE_BUTTON = "Qo'shish"
READ = "Ochish"
UPDATE = "Yangilash"
DELETE = "O'chirish"
PAY = "To'lov qilish"

# Shoe Models and Quantities
SHOE_MODELS = "Oyoq kiyim modellari"
TOTAL_QUANTITY = "Umumiy miqdori"
MODEL = "Model"
PRICE = "Narxi"
QUANTITY = "Miqdori"
TOTAL = "Jami"
STATUS = "Holati"

# Delete Confirmation Dialog
DELETE_CONFIRMATION_TITLE = "O'chirib tashlashni tasdiqlash"
DELETE_CONFIRMATION_INFO = "Haqiqatan ham bu elementni oʻchirib tashlamoqchimisiz? Bu amalni ortga qaytarib bo‘lmaydi."
DELETE_CONFIRMATION_BUTTON = "Ha, o'chirib tashla"

# Menu Items
PRODUCTS = "Mahsulotlar"
SELL = "Sotuv"
INCOME = "Daromad"
STAFFS = "Hodimlar"
DEBTS = "Qarzlar"
PRODUCEMENT = "Ishlab chiqarish"
CLIENTS = "Xaridorlar"
EXPENSES = "Xarajatlar"
ORDERS = "Buyurtmalar"
REFERENCE = "Ma'lumotnoma"

# Filters
FILTER = "Filtrlash"
CLEAN = "Tozalash"
NAME = "Ismi"
GENDER = "Jinsi"
PROFESSION = "Kasb"
PHONE_NUMBER = "Telefon raqami"
CHOOSE = "Tanlang..."

# Staff Table Details
STAFF = "Hodim"
NEW = "Yangi"
BIRTH_DATE = "Tug'ilgan sanasi"
ENTERED_DATE = "Ishga kirgan sanasi"
BALANCE = "Balans"
ACTIONS = "Amallar"
PAYMENTS_LIST = "To'lovlar ro'yxati"
WORK_LIST = "Ishlar ro'yxati"
SUM = "Summa"
DATE = "Sana"
PAYMENTS = "To'lovlar"
WORKS = "Ishlar"
NO_DATA = "Mavjud emas"




#-

COLOR = "Rangi"
LEATHER_TYPE = "Teri turi"
SOLE_TYPE = "Taglik turi"
ORDER = "Buyurtma"
WAREHOUSE = "Ombor"
PAGE = "Sahifa"
CURRENCY = "Pul birligi"
LOCATION = "Manzili"
CLIENT = "Xaridor"
TOTAL_PRICE  = "Jami narx"
DEADLINE = "Topshirish sanasi"
TYPE = "Turi"
VALUE = "Qiymati"
LEATHER = "Teri"
SOLE = "Taglik"
LINING = "Astar"
CLOSE = "Yopish"
SAVE = "Saqlash"
CANCEL = "Bekor qilish"
CREATE = "Yaratish"

EMPTY_LABEL = "---------"
KROY = "KESUV"
LAZIR = "LAZER"
ZAKATOP = "TIKUV"
KOSIB = "KOSIB"
TUQUVCHI = "TO'QUV"
CREATED = "YARATILDI"
ORDER = "Buyurtma"
SHOE_MODEL = "Oyoq kiyim modeli"
QUANTITY_TYPE = "Miqdor turi"
PRODUCEMENT_ID = "Ishlab chiqarish ID'si"
ORDER_DETAILS = "Buyurtma tafsilotlari"
COUPLE = "JUFT"
EXCEEDS_LIMIT = "Umumiy miqdor chegaradan oshib ketdi! Mavjud:"
SELLS = "Sotuv"
COMPLETED = "YAKUNLANDI"
MAIN_DETAILS = "Asosiy tafsilotlar"
BACK = "Orqaga"
ADD = "Qo'shish"
DETAIL = "Tafsilot"
MAX_ALLOWED_Q = "Bu tafsilot uchun ruxsat etilgan maksimal miqdor"
ALREADY_PRODUCED = "Allaqachon ishlab chiqarilgan"
ORDERED = "Buyurtma qilingan"
SHOE = "Oyoq kiyim"
DESCRIPTION = "Tavsif"
ACTIVE = "JARAYONDA"
CANCELED = "BEKOR QILINDI"
MALE = "ERKAK"
FEMALE = "AYOL"
USD = "USD"
UZS = "UZS"
COMPLETE_CONFIRMATION_TITLE = "Yakunlashni tasdiqlash"
COMPLETE_CONFIRMATION_INFO = "lorem ipsum dolar sit amet <br> "
COMPLETE_CONFIRMATION_BUTTON  = "Ha, o'zgartir"
ORDER_DATE_VALIDATION = "Topshirish sanasi buyurtma yaratilgan sanadan oldin bo‘lmasligi kerak."
CREATED_AT = "Yaratilgan sana"
TOQA = "To'qa"
QADOQLOVCHI = "QADOQLOVCHI"